services:
  - type: web
    name: nyamrub
    env: node
    plan: starter
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/monlam-contribution.git
    branch: staging
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
